# Generated by Django 3.2.18 on 2023-03-04 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('bystander_name', models.CharField(max_length=200)),
                ('blood_group', models.CharField(max_length=10)),
                ('required_date', models.DateField()),
                ('admitted_hospital', models.CharField(max_length=200)),
                ('bystander_no', models.BigIntegerField()),
                ('place', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('units', models.SmallIntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('patient_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('blood_group', models.CharField(max_length=10)),
                ('DOB', models.DateField()),
                ('mobile_no', models.BigIntegerField(unique=True)),
                ('state', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('email_id', models.EmailField(max_length=254)),
                ('availability', models.BooleanField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('donor_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
